// <auto-generated />
using System;
using HGTSWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HGTSWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527115039_AddVehicleCapacityAndResidenceTimezone")]
    partial class AddVehicleCapacityAndResidenceTimezone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HGTSWebApi.Models.BoardingLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Allowed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BoardedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClientTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialUid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NFCCredentialCredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RouteMismatch")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ServerTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("CredentialId");

                    b.HasIndex("NFCCredentialCredentialId");

                    b.HasIndex("TripId");

                    b.ToTable("BoardingLogs", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.DashboardUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("DashboardUsers", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActivationMode")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActivationModeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HardwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConfigUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PendingStudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TripDurationHours")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PendingStudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Devices", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Faculty", b =>
                {
                    b.Property<Guid>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FacultyId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Faculties", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Institution", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CampusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("InstitutionCode")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Institutions", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.NFCCredential", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CredentialUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DeviceIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CredentialId");

                    b.HasIndex("CredentialUid")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.HasIndex("CredentialUid", "CredentialType", "IsActive");

                    b.ToTable("NFCCredentials", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.NoGoZone", b =>
                {
                    b.Property<Guid>("NoGoZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Geometry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NoGoZoneId");

                    b.ToTable("NoGoZones", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Organization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrganizationId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Organizations", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PanicChatMessage", b =>
                {
                    b.Property<Guid>("PanicChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PanicEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PanicEventId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PanicChatMessageId");

                    b.HasIndex("PanicEventId");

                    b.HasIndex("PanicEventId1");

                    b.ToTable("PanicChatMessages", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PanicEvent", b =>
                {
                    b.Property<Guid>("PanicEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanicEventId");

                    b.ToTable("PanicEvents", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PickupZone", b =>
                {
                    b.Property<Guid>("PickupZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PickupZoneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PickupZoneId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("PickupZoneCode")
                        .IsUnique();

                    b.ToTable("PickupZones", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Placement", b =>
                {
                    b.Property<Guid>("PlacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlacementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlacementId");

                    b.HasIndex("RouteId");

                    b.HasIndex("StudentId");

                    b.ToTable("Placements", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Residence", b =>
                {
                    b.Property<Guid>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PickupZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResidenceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResidenceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResidenceId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("PickupZoneId");

                    b.HasIndex("ResidenceCode")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.ToTable("Residences", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.RouteStop", b =>
                {
                    b.Property<Guid>("RouteStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DwellMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedTravelMinutesFromPrevious")
                        .HasColumnType("int");

                    b.Property<Guid>("ResidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RouteStopId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CellNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.StudentAuth", b =>
                {
                    b.Property<Guid>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("StudentId1")
                        .IsUnique()
                        .HasFilter("[StudentId1] IS NOT NULL");

                    b.ToTable("StudentAuths", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmergencyReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmergencyEnded")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SwappedFromTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SwappedToTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BusId");

                    b.HasKey("TripId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("RouteId");

                    b.HasIndex("SwappedFromTripId");

                    b.HasIndex("SwappedToTripId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.TripStop", b =>
                {
                    b.Property<Guid>("TripStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PassengersAlighted")
                        .HasColumnType("int");

                    b.Property<int>("PassengersBoarded")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlannedArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteStopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TripStopId");

                    b.HasIndex("RouteStopId");

                    b.HasIndex("TripId");

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("HGTSWebApi.Models.TripTransfer", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DashboardUserUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NewTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OriginalTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransferredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransferId");

                    b.HasIndex("DashboardUserUserId");

                    b.HasIndex("NewTripId");

                    b.HasIndex("OriginalTripId");

                    b.HasIndex("TransferredBy");

                    b.HasIndex("VehicleId");

                    b.ToTable("TripTransfers", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BusId");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BusLabel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.ToTable("Buses", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.VehicleRoute", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PickupZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResidenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RouteId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("PickupZoneId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("RouteCode")
                        .IsUnique();

                    b.ToTable("BusRoutes", "dbo");
                });

            modelBuilder.Entity("TripTrip", b =>
                {
                    b.Property<Guid>("InverseSwappedFromTripTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InverseSwappedToTripTripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InverseSwappedFromTripTripId", "InverseSwappedToTripTripId");

                    b.HasIndex("InverseSwappedToTripTripId");

                    b.ToTable("TripTrip", "dbo");
                });

            modelBuilder.Entity("HGTSWebApi.Models.BoardingLog", b =>
                {
                    b.HasOne("HGTSWebApi.Models.NFCCredential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.NFCCredential", null)
                        .WithMany("BoardingLogs")
                        .HasForeignKey("NFCCredentialCredentialId");

                    b.HasOne("HGTSWebApi.Models.Trip", "Trip")
                        .WithMany("BoardingLogs")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Credential");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("HGTSWebApi.Models.DashboardUser", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Organization", null)
                        .WithMany("DashboardUsers")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Device", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Organization", null)
                        .WithMany("Devices")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("HGTSWebApi.Models.Student", "PendingStudent")
                        .WithMany()
                        .HasForeignKey("PendingStudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.Student", null)
                        .WithMany("Devices")
                        .HasForeignKey("StudentId");

                    b.Navigation("PendingStudent");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Faculty", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Institution", "Institution")
                        .WithMany("Faculties")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Institution", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Organization", "Organization")
                        .WithMany("Institutions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HGTSWebApi.Models.NFCCredential", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Student", "Student")
                        .WithMany("Credentials")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PanicChatMessage", b =>
                {
                    b.HasOne("HGTSWebApi.Models.PanicEvent", "PanicEvent")
                        .WithMany()
                        .HasForeignKey("PanicEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.PanicEvent", null)
                        .WithMany("PanicChatMessages")
                        .HasForeignKey("PanicEventId1");

                    b.Navigation("PanicEvent");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PickupZone", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Institution", "Institution")
                        .WithMany("PickupZones")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Placement", b =>
                {
                    b.HasOne("HGTSWebApi.Models.VehicleRoute", "Route")
                        .WithMany("Placements")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.Student", "Student")
                        .WithMany("Placements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Residence", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Institution", "Institution")
                        .WithMany("Residences")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.PickupZone", "PickupZone")
                        .WithMany("Residences")
                        .HasForeignKey("PickupZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.VehicleRoute", "Route")
                        .WithMany("Residences")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institution");

                    b.Navigation("PickupZone");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("HGTSWebApi.Models.RouteStop", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.VehicleRoute", "Route")
                        .WithMany("RouteStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Student", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.Institution", "Institution")
                        .WithMany("Students")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Residence", "Residence")
                        .WithMany("Students")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Faculty");

                    b.Navigation("Institution");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("HGTSWebApi.Models.StudentAuth", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Student", "Student")
                        .WithOne()
                        .HasForeignKey("HGTSWebApi.Models.StudentAuth", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Student", null)
                        .WithOne("StudentAuth")
                        .HasForeignKey("HGTSWebApi.Models.StudentAuth", "StudentId1");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Trip", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Device", "Device")
                        .WithMany("Trips")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Residence", "Residence")
                        .WithMany("Trips")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.VehicleRoute", "BusRoute")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Trip", "SwappedFromTrip")
                        .WithMany()
                        .HasForeignKey("SwappedFromTripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HGTSWebApi.Models.Trip", "SwappedToTrip")
                        .WithMany()
                        .HasForeignKey("SwappedToTripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HGTSWebApi.Models.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Device");

                    b.Navigation("Residence");

                    b.Navigation("SwappedFromTrip");

                    b.Navigation("SwappedToTrip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("HGTSWebApi.Models.TripStop", b =>
                {
                    b.HasOne("HGTSWebApi.Models.RouteStop", "RouteStop")
                        .WithMany("TripStops")
                        .HasForeignKey("RouteStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Trip", "Trip")
                        .WithMany("TripStops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteStop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("HGTSWebApi.Models.TripTransfer", b =>
                {
                    b.HasOne("HGTSWebApi.Models.DashboardUser", null)
                        .WithMany("TripTransferDashboardUserUsers")
                        .HasForeignKey("DashboardUserUserId");

                    b.HasOne("HGTSWebApi.Models.Trip", "NewTrip")
                        .WithMany("TripTransferNewTrips")
                        .HasForeignKey("NewTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Trip", "OriginalTrip")
                        .WithMany("TripTransferOriginalTrips")
                        .HasForeignKey("OriginalTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.DashboardUser", "TransferredByNavigation")
                        .WithMany("TripTransferTransferredByNavigations")
                        .HasForeignKey("TransferredBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HGTSWebApi.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewTrip");

                    b.Navigation("OriginalTrip");

                    b.Navigation("TransferredByNavigation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("HGTSWebApi.Models.VehicleRoute", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Institution", "Institution")
                        .WithMany("Routes")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.PickupZone", "PickupZone")
                        .WithMany("Routes")
                        .HasForeignKey("PickupZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HGTSWebApi.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institution");

                    b.Navigation("PickupZone");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("TripTrip", b =>
                {
                    b.HasOne("HGTSWebApi.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("InverseSwappedFromTripTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HGTSWebApi.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("InverseSwappedToTripTripId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HGTSWebApi.Models.DashboardUser", b =>
                {
                    b.Navigation("TripTransferDashboardUserUsers");

                    b.Navigation("TripTransferTransferredByNavigations");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Device", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Institution", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("PickupZones");

                    b.Navigation("Residences");

                    b.Navigation("Routes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("HGTSWebApi.Models.NFCCredential", b =>
                {
                    b.Navigation("BoardingLogs");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Organization", b =>
                {
                    b.Navigation("DashboardUsers");

                    b.Navigation("Devices");

                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PanicEvent", b =>
                {
                    b.Navigation("PanicChatMessages");
                });

            modelBuilder.Entity("HGTSWebApi.Models.PickupZone", b =>
                {
                    b.Navigation("Residences");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Residence", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("HGTSWebApi.Models.RouteStop", b =>
                {
                    b.Navigation("TripStops");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Student", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Devices");

                    b.Navigation("Placements");

                    b.Navigation("StudentAuth");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Trip", b =>
                {
                    b.Navigation("BoardingLogs");

                    b.Navigation("TripStops");

                    b.Navigation("TripTransferNewTrips");

                    b.Navigation("TripTransferOriginalTrips");
                });

            modelBuilder.Entity("HGTSWebApi.Models.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("HGTSWebApi.Models.VehicleRoute", b =>
                {
                    b.Navigation("Placements");

                    b.Navigation("Residences");

                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
